# Generated by Django 4.2.2 on 2023-06-30 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_usrprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsfeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('newsimg', models.ImageField(upload_to='news/')),
                ('datez', models.DateField(auto_now=True)),
                ('des', models.CharField(max_length=2000)),
                ('usr', models.ManyToManyField(related_name='newsfeed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
