# Generated by Django 4.2.2 on 2023-07-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_newsfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productss',
            name='breif',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='productss',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
